export const iconLabels: Record<string, string> = {
  nextjs: 'Next.js',
  tanstack: 'TanStack Start',
  reactjs: 'React',
  typescript: 'TypeScript',
  javascript: 'JavaScript',
  tailwindcss: 'Tailwind CSS',
  trpc: 'tRPC',
  convex: 'Convex',
  vite: 'Vite',
  'shadcn-ui': 'shadcn/ui',
  prisma: 'Prisma',
  drizzle: 'Drizzle',
  nodejs: 'Node.js',
  express: 'Express',
  mongodb: 'MongoDB',
  postgresql: 'PostgreSQL',
  redis: 'Redis',
  graphql: 'GraphQL',
  docker: 'Docker',
  aws: 'AWS',
  vercel: 'Vercel',
  supabase: 'Supabase',
  firebase: 'Firebase',
  clerk: 'Clerk',
  zod: 'Zod',
  zustand: 'Zustand',
  'framer-motion': 'Framer Motion',
  'radix-ui': 'Radix UI',
  neondb: 'Neon',
  'tanstack-query': 'TanStack Query',
  astro: 'Astro',
  expo: 'Expo',
  svelte: 'Svelte',
  hono: 'Hono',
  'cloudflare-workers': 'Cloudflare Workers',
};
